info:
  version: 1.0.0
  description: nil
  title: Events API
components:
  responses: {}
  requestBodies: {}
  schemas:
    IdxPlayer:
      type: object
      required:
        - mainframe_id
      properties:
        mainframe_id:
          type: integer
    index_requested:
      type: object
      required:
        - player
      properties:
        player:
          $ref: '#/components/schemas/IdxPlayer'
openapi: 3.1.0
paths: {}
