info:
  version: 1.0.0
  description: nil
  title: Events API
components:
  responses: {}
  requestBodies: {}
  schemas:
    IdxEndpoint:
      type: object
      required:
        - logs
        - nip
      properties:
        nip:
          type: string
        logs:
          type: array
          items:
            $ref: '#/components/schemas/IdxLog'
    IdxGateway:
      type: object
      required:
        - logs
        - tunnels
        - nip
        - id
      properties:
        id:
          type: integer
        nip:
          type: string
        tunnels:
          type: array
          items:
            $ref: '#/components/schemas/IdxTunnel'
        logs:
          type: array
          items:
            $ref: '#/components/schemas/IdxLog'
    IdxLog:
      type: object
      required:
        - revision_id
        - type
        - id
      properties:
        id:
          type: integer
        type:
          type: string
        revision_id:
          type: integer
    IdxPlayer:
      type: object
      required:
        - mainframe_id
        - gateways
        - endpoints
      properties:
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/IdxEndpoint'
        gateways:
          type: array
          items:
            $ref: '#/components/schemas/IdxGateway'
        mainframe_id:
          type: integer
    IdxTunnel:
      type: object
      required:
        - source_nip
        - target_nip
        - tunnel_id
      properties:
        tunnel_id:
          type: integer
        target_nip:
          type: string
        source_nip:
          type: string
    file_delete_failed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: integer
    file_deleted:
      type: object
      required:
        - process_id
        - file_id
      properties:
        file_id:
          type: integer
        process_id:
          type: integer
    file_install_failed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: integer
    file_installed:
      type: object
      required:
        - memory_usage
        - process_id
        - installation_id
        - file_name
      properties:
        file_name:
          type: string
        installation_id:
          type: integer
        process_id:
          type: integer
        memory_usage:
          type: integer
    index_requested:
      type: object
      required:
        - player
      properties:
        player:
          $ref: '#/components/schemas/IdxPlayer'
    process_created:
      type: object
      required:
        - type
        - id
      properties:
        id:
          type: integer
        type:
          type: string
    tunnel_created:
      type: object
      required:
        - source_nip
        - target_nip
        - tunnel_id
        - index
        - access
      properties:
        access:
          type: string
        index:
          $ref: '#/components/schemas/IdxEndpoint'
        tunnel_id:
          type: integer
        target_nip:
          type: string
        source_nip:
          type: string
  securitySchemes: {}
openapi: 3.1.0
paths: {}
