info:
  version: 1.0.0
  description: nil
  title: Events API
components:
  responses: {}
  requestBodies: {}
  schemas:
    index_requested:
      type: object
      required:
        - foo
      properties:
        foo:
          type: string
openapi: 3.1.0
paths: {}
