info:
  version: 1.0.0
  description: nil
  title: Events API
components:
  responses: {}
  requestBodies: {}
  schemas:
    IdxEndpoint:
      type: object
      required:
        - nip
        - logs
        - processes
      properties:
        processes:
          type: array
          items:
            $ref: '#/components/schemas/IdxProcess'
        logs:
          type: array
          items:
            $ref: '#/components/schemas/IdxLog'
        nip:
          type: string
    IdxGateway:
      type: object
      required:
        - tunnels
        - nip
        - logs
        - processes
      properties:
        processes:
          type: array
          items:
            $ref: '#/components/schemas/IdxProcess'
        logs:
          type: array
          items:
            $ref: '#/components/schemas/IdxLog'
        nip:
          type: string
        tunnels:
          type: array
          items:
            $ref: '#/components/schemas/IdxTunnel'
    IdxLog:
      type: object
      required:
        - sort_strategy
        - is_deleted
        - revision_count
        - revisions
        - id
      properties:
        id:
          type: string
        revisions:
          type: array
          items:
            $ref: '#/components/schemas/IdxLogRevision'
        revision_count:
          type: integer
        is_deleted:
          type: boolean
        sort_strategy:
          type: string
    IdxLogRevision:
      type: object
      required:
        - revision_id
        - direction
        - source
        - type
        - data
      properties:
        data:
          type: string
        type:
          type: string
        source:
          type: string
        direction:
          type: string
        revision_id:
          type: integer
    IdxPlayer:
      type: object
      required:
        - mainframe_nip
        - gateways
        - endpoints
      properties:
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/IdxEndpoint'
        gateways:
          type: array
          items:
            $ref: '#/components/schemas/IdxGateway'
        mainframe_nip:
          type: string
    IdxProcess:
      type: object
      required:
        - process_id
        - type
        - data
      properties:
        data:
          type: string
        type:
          type: string
        process_id:
          type: string
    IdxTunnel:
      type: object
      required:
        - source_nip
        - target_nip
        - tunnel_id
      properties:
        tunnel_id:
          type: string
        target_nip:
          type: string
        source_nip:
          type: string
    file_delete_failed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: string
    file_deleted:
      type: object
      required:
        - process_id
        - file_id
      properties:
        file_id:
          type: string
        process_id:
          type: string
    file_install_failed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: string
    file_installed:
      type: object
      required:
        - memory_usage
        - process_id
        - installation_id
        - file_name
      properties:
        file_name:
          type: string
        installation_id:
          type: string
        process_id:
          type: string
        memory_usage:
          type: integer
    file_transfer_failed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: string
    file_transferred:
      type: object
      required:
        - process_id
        - file_id
      properties:
        file_id:
          type: string
        process_id:
          type: string
    index_requested:
      type: object
      required:
        - player
      properties:
        player:
          $ref: '#/components/schemas/IdxPlayer'
    installation_uninstall_failed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: string
    installation_uninstalled:
      type: object
      required:
        - process_id
        - installation_id
      properties:
        installation_id:
          type: string
        process_id:
          type: string
    log_delete_failed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: string
    log_deleted:
      type: object
      required:
        - nip
        - process_id
        - log_id
      properties:
        log_id:
          type: string
        process_id:
          type: string
        nip:
          type: string
    log_edit_failed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: string
    log_edited:
      type: object
      required:
        - nip
        - process_id
        - log_id
      properties:
        log_id:
          type: string
        process_id:
          type: string
        nip:
          type: string
    process_completed:
      type: object
      required:
        - nip
        - process_id
        - type
        - data
      properties:
        data:
          type: string
        type:
          type: string
        process_id:
          type: string
        nip:
          type: string
    process_created:
      type: object
      required:
        - nip
        - process_id
        - type
        - data
      properties:
        data:
          type: string
        type:
          type: string
        process_id:
          type: string
        nip:
          type: string
    process_killed:
      type: object
      required:
        - process_id
        - reason
      properties:
        reason:
          type: string
        process_id:
          type: string
    tunnel_created:
      type: object
      required:
        - source_nip
        - target_nip
        - tunnel_id
        - index
        - access
      properties:
        access:
          type: string
        index:
          $ref: '#/components/schemas/IdxEndpoint'
        tunnel_id:
          type: string
        target_nip:
          type: string
        source_nip:
          type: string
  securitySchemes: {}
openapi: 3.1.0
paths: {}
