info:
  version: 1.0.0
  description: nil
  title: Events API
components:
  responses: {}
  schemas:
    IdxGateway:
      type: object
      required:
        - logs
        - id
      properties:
        id:
          type: integer
        logs:
          type: array
          items:
            $ref: '#/components/schemas/IdxLog'
    IdxLog:
      type: object
      required:
        - revision_id
        - type
        - id
      properties:
        id:
          type: integer
        type:
          type: string
        revision_id:
          type: integer
    IdxPlayer:
      type: object
      required:
        - mainframe_id
        - gateways
      properties:
        gateways:
          type: array
          items:
            $ref: '#/components/schemas/IdxGateway'
        mainframe_id:
          type: integer
    index_requested:
      type: object
      required:
        - player
      properties:
        player:
          $ref: '#/components/schemas/IdxPlayer'
    tunnel_created:
      type: object
      required:
        - source_nip
        - target_nip
        - tunnel_id
        - access
      properties:
        access:
          type: string
        tunnel_id:
          type: string
        target_nip:
          type: string
        source_nip:
          type: string
  requestBodies: {}
openapi: 3.1.0
paths: {}
