info:
  version: 1.0.0
  description: nil
  title: Game API
components:
  responses:
    GenericBadRequestResponse:
      description: TODO
      content:
        application/json:
          schema:
            type: object
            required:
              - error
            properties:
              error:
                $ref: '#/components/schemas/GenericBadRequest'
    GenericErrorResponse:
      description: TODO
      content:
        application/json:
          schema:
            type: object
            required:
              - error
            properties:
              error:
                $ref: '#/components/schemas/GenericError'
    GenericUnauthorizedResponse:
      description: TODO
      content: {}
    PlayerSyncOkResponse:
      description: TODO description
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                $ref: '#/components/schemas/PlayerSyncOutput'
    ServerLoginOkResponse:
      description: TODO description
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                $ref: '#/components/schemas/ServerLoginOutput'
  schemas:
    GenericBadRequest:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
        details:
          type: string
    GenericError:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
        details:
          type: string
    PlayerSyncInput:
      type: object
      required: []
      properties:
        token:
          type: string
    PlayerSyncOutput:
      type: object
      required: []
      properties: {}
    ServerLoginInput:
      type: object
      required: []
      properties:
        tunnel_id:
          type: integer
    ServerLoginOutput:
      type: object
      required: []
      properties: {}
  requestBodies:
    PlayerSyncRequest:
      description: TODO description
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PlayerSyncInput'
    ServerLoginRequest:
      description: TODO description
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerLoginInput'
openapi: 3.1.0
paths:
  /v1/player/sync:
    post:
      responses:
        '200':
          $ref: '#/components/responses/PlayerSyncOkResponse'
        '400':
          $ref: '#/components/responses/GenericBadRequestResponse'
      operationId: PlayerSync
      requestBody:
        $ref: '#/components/requestBodies/PlayerSyncRequest'
  /v1/server/{nip}/login/{target_nip}:
    post:
      parameters:
        - in: path
          name: nip
          description: ''
          required: true
          schema:
            type: string
        - in: path
          name: target_nip
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ServerLoginOkResponse'
      operationId: ServerLogin
      requestBody:
        $ref: '#/components/requestBodies/ServerLoginRequest'
