info:
  version: 1.0.0
  description: nil
  title: Lobby API
components:
  responses:
    GenericErrorResponse:
      description: TODO
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
    GenericUnauthorizedResponse:
      description: TODO
      content: {}
    UserLoginOkResponse:
      description: TODO Description
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                $ref: '#/components/schemas/UserLoginOutput'
    UserRegisterOkResponse:
      description: TODO Description
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                $ref: '#/components/schemas/UserRegisterOutput'
  requestBodies:
    UserLoginRequest:
      description: TODO descriptioin
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserLoginInput'
    UserRegisterRequest:
      description: TODO descriptioin
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRegisterInput'
  schemas:
    GenericError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    UserLoginInput:
      type: object
      required:
        - password
        - email
      properties:
        email:
          type: string
        password:
          type: string
    UserLoginOutput:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    UserRegisterInput:
      type: object
      required:
        - username
        - password
        - email
      properties:
        email:
          type: string
        password:
          type: string
        username:
          type: string
    UserRegisterOutput:
      type: object
      required:
        - id
      properties:
        id:
          type: string
openapi: 3.1.0
paths:
  /v1/user/login:
    post:
      responses:
        '200':
          $ref: '#/components/responses/UserLoginOkResponse'
        '401':
          $ref: '#/components/responses/GenericUnauthorizedResponse'
        '422':
          $ref: '#/components/responses/GenericErrorResponse'
      operationId: UserLogin
      requestBody:
        $ref: '#/components/requestBodies/UserLoginRequest'
  /v1/user/register:
    post:
      responses:
        '200':
          $ref: '#/components/responses/UserRegisterOkResponse'
        '422':
          $ref: '#/components/responses/GenericErrorResponse'
      operationId: UserRegister
      requestBody:
        $ref: '#/components/requestBodies/UserRegisterRequest'
