Mox.defmock(Webserver.EndpointMock, for: Webserver.Endpoint.Behaviour)
Mox.defmock(Webserver.Conveyor.BeltMock, for: Webserver.Conveyor.Belt)
Mox.defmock(Core.EventMock, for: :"Elixir.Core.Event")
Mox.defmock(Game.Scanner.ScanneableMock, for: :"Elixir.Game.Scanner.Scanneable")
Mox.defmock(Hotel.Log.ExporterMock, for: Hotel.Log.Exporter)
