defmodule Game.Log.ID, do: use(Core.ID)
defmodule Game.Server.ID, do: use(Core.ID)
defmodule Game.Connection.ID, do: use(Core.ID)
defmodule Game.ConnectionGroup.ID, do: use(Core.ID)
defmodule Game.Tunnel.ID, do: use(Core.ID)
