name: Helix
on: [push]

env:
  MIX_ENV: test

jobs:
  tests:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ./helix

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup backend environment
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict


      # TODO: Why _both_ deps and _build being cached? Is that okay?
      - name: Restore build cache
        uses: actions/cache@v2
        id: mix_cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        if: steps.mix_cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Test app
        run: mix test
