name: Helix
on: [push]

jobs:
  tests:
    runs-on: ubuntu-24.04

    env:
      MIX_ENV: test
      HELIX_TEST_DATA_DIR: tmp/helix_test

    defaults:
      run:
        working-directory: ./helix

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup backend environment
        uses: erlef/setup-beam@v1
        with:
          version-file: helix/.tool-versions
          version-type: strict

      - name: Setup database directories
        run: mkdir -p tmp/helix_test/{lobby,singleplayer,multiplayer,sp_player,mp_player,sp_server,mp_server}

      - name: Restore deps cache
        uses: actions/cache@v4
        id: mix_cache
        with:
          path: |
            helix/deps
            helix/_build
            helix/priv/native
          key: ${{ runner.os }}-mix-${{ hashFiles('helix/mix.lock') }}-${{ hashFiles('helix/native/**/Cargo.lock') }}

      - name: Install Elixir Dependencies
        if: steps.mix_cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: "Get current commit hash"
        run: echo "CURRENT_COMMIT_HASH=$(git log -1 --format=%h)" >> $GITHUB_ENV

      - name: "Get previous commit hash"
        run: echo "PREV_COMMIT_HASH=$(git log -2 --format=%h | tail -n +2)" >> $GITHUB_ENV

      - name: Restore Helix build cache
        uses: actions/cache@v4
        id: helix_cache
        with:
          path: |
            helix/_build/test/lib/helix
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.PREV_COMMIT_HASH }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}

      - name: Compile app
        run: mix compile --warnings-as-errors

      # This is the equivalent of `apt-get install <packages>` but with built-in cache. Note it may
      # not work well with packages that have pre/post installation scripts
      - name: Install OS dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: yq
          version: 1.0

      - name: Compile app
        run: mix compile --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted

      # TODO: Consider moving this to `linters`. It does a force-compilation (and doesn't need to happen in TEST, albeit harmless)
      - name: Validate feebdb_schemas.json is up-to-date
        run: mix feeb_db.list_schemas && git diff --exit-code --no-ext-diff

      - name: Test app
        run: mix test

      - name: Check for transitive compilation dependencies
        run: mix xref graph --label compile-connected --fail-above 0

      # Uncomment below once repository is public (so we can use coveralls.io)
      # - name: Test app
      #   run: mix coveralls.github
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: I'm unsure about `Uncache Helix`. I'll leave it uncommented (cached) for a while and
      # see whether it causes any problems. For a more robust CI, we may want a separate
      # "pre-release" build which performs a full build, but for the vast majority of CI checks we
      # don't need such strict requirements.
      # # Force a full Helix compilation on every CI run.
      # - name: Uncache Helix
      #   run: rm -rf _build/{dev,test}/lib/helix

      # Now the next commit we push to the PR will use this cached entry as starting point
      # Note it uses the cache/save action, so it will not attempt a restore
      - name: Cache the build for this commit
        uses: actions/cache/save@v4
        id: new_helix_cache
        with:
          path: helix/_build/test/lib/helix
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.CURRENT_COMMIT_HASH }}
